ec2:

  AWS_ACCESS_KEY_ID: '<>'
  AWS_SECRET_ACCESS_KEY: '<>'
  region: us-west-2
  credentials: kubenodes
  image: ami-835b4efa
  instance_type: t2.micro
  vpc_subnet_id: subnet-5381541f
  public_ip: yes
  tags:
    Name: webserver
  volumes:
    - device_name: /dev/xvda
      volume_type: standard
      volume_size: 8
